### PR TITLE
fix: change defaults

### PR DESCRIPTION
**Pull request by okikio**
### Initial checklist

* [x] I read the support docs 
* [x] I read the contributing guide 
* [x] I agree to follow the code of conduct 
* [x] I searched issues and couldn’t find anything (or linked relevant results below) 
* [x] If applicable, I’ve added docs and tests

### Description of changes

Change defaults to not add target, rel should just be ['nofollow']

fix for #1

### CODE REVIEW

**Comment by okikio** [comment]
cc @wooorm I've fixed issue #1. I've edited the docs and updated tests

**Comment by wooorm** [comment]
Can you *just* PR [`1601635` (#5)](https://github.com/rehypejs/rehype-external-links/pull/5/commits/16016350b239a3ec56eef77a11cdcb9465e8f06e), instead of everything?
Also, run `npm test` to format everything according to the project style. It looks like you are using different tools.

**Comment by okikio** [comment]
I'll create a new pr specifically with only the changes [1601635](https://github.com/rehypejs/rehype-external-links/pull/5/commits/16016350b239a3ec56eef77a11cdcb9465e8f06e). 

I did run `npm run test`, maybe I just forgot to commit and changes in formatting

**Comment by okikio** [comment]
I've created #6 as a replacement to this pr

**Pull request closed without merging**
